name: Android development CI

on:
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          submodules: 'true'
      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY }}
          ENCODED_PROPS: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          if [ "$ENCODED_PROPS" == "" ]; then
            exit
          fi
          echo $ENCODED_KEYSTORE | base64 -di > keystore.jks
          echo $ENCODED_PROPS | base64 -di > keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Calculate version suffix
        run:
          echo "VERSION_SUFFIX=$(git show -s --abbrev=7 --format=-%cd-%h --date=format:%y%m%d)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew assembleEmulatorRelease

      - name: Prepare artifact
        run: |
          mkdir -p artifact/mapping
          mv app/build/outputs/native-debug-symbols/**/* artifact
          mv app/build/outputs/mapping/**/* artifact/mapping
          (cd artifact && zip -r "$OLDPWD/symbols.zip" .)

      - name: GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          title: "Development Build"
          files: |
            app/build/outputs/apk/**/*.apk
            symbols.zip

      - name: Upload Artifact (bin)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "Binary"
          path: app/build/outputs/apk/emulator/release/*.apk

      - name: Upload a Build Artifact (sym)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "Symbols"
          path: artifact
